#!/bin/sh -eu
arch="${1:-amd64}"
export netbsd_dist="ftp://ftp.netbsd.org/pub/NetBSD/NetBSD-8.0/$arch/"
export pkgsrc_dist="ftp://ftp.netbsd.org/pub/pkgsrc/current/pkgsrc.tar.gz"
export pkgin_dist="ftp://ftp.netbsd.org/pub/pkgsrc/packages/NetBSD/$arch/8.0/All"
exec ../genimg "$@"
