#!/usr/bin/env python3
# We just let everyone in at this stage, authentication is done later on.
from srht.config import cfg
import sys
import os

key_type = sys.argv[3]
b64key = sys.argv[4]

default_shell = os.path.join(os.path.dirname(sys.argv[0]), "buildsrht-shell")
shell = cfg("builds.sr.ht", "shell", default=default_shell)
keys = ("command=\"{} '{}'\",".format(shell, b64key) +
    "no-port-forwarding,no-X11-forwarding,no-agent-forwarding" +
    " {} {} somebody".format(key_type, b64key) + "\n")
print(keys)
sys.exit(0)
