#!/bin/sh
arch="${1:-amd64}"
export release="12.1-RELEASE"
export dist_base="https://download.freebsd.org/ftp/releases/$arch/$release"
export ports_base="https://download.freebsd.org/ftp/snapshots/$arch/12.1-STABLE"
exec ../genimg "$@"
