#!/usr/bin/env bash
guest_kernel=kernel
guest_initrd=initrd
poweroff_cmd="sudo systemctl poweroff"

install() {
    port=$1
    shift 1
    guest_ssh -p $port build@localhost EDITOR=true yay --noconfirm -Syu "$@"
}

add_repository() {
    port=$1
    name=$2
    src=$3
    repo=$(echo $src | cut -d'#' -f1)
    key=$(echo $src | cut -d'#' -f2)
    printf '[%s]\nServer = %s\n' "$name" "$repo" \
        | guest_ssh -p $port build@localhost sudo tee -a /etc/pacman.conf
    guest_ssh -p $port build@localhost sudo pacman-key -r $key
    guest_ssh -p $port build@localhost sudo pacman-key --lsign-key $key
    guest_ssh -p $port build@localhost sudo pacman -Sy
}

sanity_check() {
    boot 8022 &
    qemu=$!
    sleep 5
    echo "Testing sudo..."
    guest_ssh -p 8022 build@localhost sudo ls -a
    echo "Testing networking..."
    guest_ssh -p 8022 build@localhost curl http://example.org
    echo "Testing pacman..."
    guest_ssh -p 8022 build@localhost sudo pacman -Syu --noconfirm
    echo "Testing git..."
    guest_ssh -p 8022 build@localhost git --version
    echo "Testing AUR packages..."
    install 8022 brightnessctl
    echo "Everything works!"
    guest_ssh -p 8022 build@localhost sudo systemctl poweroff || true
    wait $qemu
    cleanup 8022
}
