"""Add job ID to tasks

Revision ID: 37f89559055c
Revises: None
Create Date: 2017-04-10 08:55:29.742324

"""

# revision identifiers, used by Alembic.
revision = '37f89559055c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('runner', sa.String(), nullable=True))
    op.add_column('task', sa.Column('job_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task', 'job', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'job_id')
    op.drop_column('job', 'runner')
    # ### end Alembic commands ###
