"""Add tags column

Revision ID: dfaa14e71ccf
Revises: e17c2b5aa90e
Create Date: 2017-04-16 21:02:28.869369

"""

# revision identifiers, used by Alembic.
revision = 'dfaa14e71ccf'
down_revision = 'e17c2b5aa90e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'tags')
    # ### end Alembic commands ###
