"""Delete name from job

Revision ID: e17c2b5aa90e
Revises: 37f89559055c
Create Date: 2017-04-10 10:17:44.128441

"""

# revision identifiers, used by Alembic.
revision = 'e17c2b5aa90e'
down_revision = '37f89559055c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
