#!/bin/sh
poweroff_cmd="sudo poweroff"
default_arch=x86_64

boot() {
	if [ "$arch" != "x86_64" ]
	then
		echo "Unsupported architecture $arch" >&2
		exit 1
	fi
	_boot $(cpu_opts x86_64)
}

install() {
	port=$1
	shift 1
	guest_ssh -p $port build@127.0.0.1 nix-channel --update
	guest_ssh -p $port build@127.0.0.1 nix-env -iA "$@"
}

add_repository() {
	port=$1
	shift 1
	guest_ssh -p $port build@127.0.0.1 nix-channel --add "$@"
	guest_ssh -p $port build@127.0.0.1 nix-channel --update
}

sanity_check() {
	echo "Booting..."
	cmd_boot x86_64 8022 qemu &
	trap 'cmd_cleanup 8022' EXIT
	_wait_boot 8022
	echo "Testing sudo..."
	guest_ssh -p 8022 build@127.0.0.1 sudo ls -a
	echo "Testing networking..."
	guest_ssh -p 8022 build@127.0.0.1 curl https://example.org
	echo "Testing nix..."
	add_repository 8022 https://nixos.org/channels/nixpkgs-unstable
	guest_ssh -p 8022 build@127.0.0.1 nix-shell -p hello --run "hello"
	echo "Testing git..."
	guest_ssh -p 8022 build@127.0.0.1 git --version
	echo "Everything works!"
	guest_ssh -p 8022 build@127.0.0.1 sudo poweroff || true
}

